openapi: 3.0.1
info:
  title: Month-and-math service OpenAPI 3.0
  version: v1.0
  description: |-
    # Introduction
    This is a Month and Math Service API. It allows you to get a random month, search for month based on input, and perform math operations.
    # Month Routes
    Month routes include the get a random month and search for a month using a integer. At /randomMonth you will get a single month ranging from January to December. At /month/{monthNumber} you will get a month relative to the monthNumber give, range 1-12.
    # Math Operations
    Math Operations include add, subtract, divide, and multiply. Depending upon which route is called will allow for different operations. Answers are integers.
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /subtract:
    post:
      tags:
        - month-math-controller
      operationId: subtractInt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subtract'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolutionSubtract'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
  /multiply:
    post:
      tags:
        - month-math-controller
      operationId: multiplyInt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Multiply'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolutionMultiply'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
  /divide:
    post:
      tags:
        - month-math-controller
      operationId: divideInt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Divide'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolutionDivide'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
  /add:
    post:
      tags:
        - month-math-controller
      operationId: addInt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Add'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MathSolutionAdd'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
  /randomMonth:
    get:
      tags:
        - month-math-controller
      operationId: randomMonth
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Month'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
  /month/{monthNumber}:
    get:
      tags:
        - month-math-controller
      operationId: monthConverter
      parameters:
        - name: monthNumber
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Month'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errorMessage:
          type: string
          example: invalid input
        status:
          type: integer
          format: int32
          example: 422
        errorCode:
          type: string
          example: 422 UNPROCESSABLE_ENTITY
        time:
          type: string
          format: date-time
    Add:
        required:
          - operand1
          - operand2
        type: object
        properties:
          operand1:
            type: integer
            format: int32
            example: 1
          operand2:
            type: integer
            format: int32
            example: 1
    Subtract:
        required:
          - operand1
          - operand2
        type: object
        properties:
          operand1:
            type: integer
            format: int32
            example: 1
          operand2:
            type: integer
            format: int32
            example: 1
    Multiply:
        required:
          - operand1
          - operand2
        type: object
        properties:
          operand1:
            type: integer
            format: int32
            example: 2
          operand2:
            type: integer
            format: int32
            example: 4
    Divide:
        required:
          - operand1
          - operand2
        type: object
        properties:
          operand1:
            type: integer
            format: int32
            example: 10
          operand2:
            type: integer
            format: int32
            example: 2
    MathSolutionAdd:
      required:
        - operand1
        - operand2
      type: object
      properties:
        operand1:
          type: integer
          format: int32
          example: 1
        operand2:
          type: integer
          format: int32
          example: 1
        operation:
          type: string
          example: add
        answer:
          type: integer
          format: int32
          example: 2
    MathSolutionSubtract:
      required:
        - operand1
        - operand2
      type: object
      properties:
        operand1:
          type: integer
          format: int32
          example: 5
        operand2:
          type: integer
          format: int32
          example: 1
        operation:
          type: string
          example: subtract
        answer:
          type: integer
          format: int32
          example: 4
    MathSolutionDivide:
      required:
        - operand1
        - operand2
      type: object
      properties:
        operand1:
          type: integer
          format: int32
          example: 10
        operand2:
          type: integer
          format: int32
          example: 5
        operation:
          type: string
          example: divide
        answer:
          type: integer
          format: int32
          example: 2
    MathSolutionMultiply:
      required:
        - operand1
        - operand2
      type: object
      properties:
        operand1:
          type: integer
          format: int32
          example: 2
        operand2:
          type: integer
          format: int32
          example: 3
        operation:
          type: string
          example: multiply
        answer:
          type: integer
          format: int32
          example: 6
    Month:
      type: object
      properties:
        number:
          maximum: 12
          minimum: 1
          type: integer
          format: int32
        name:
          type: string
          example: January
